6758881: (launcher) needs to throw NoClassDefFoundError instead of JavaRuntimeException Summary: The launcher will throw the Error vs. Exception, also fixed some minor issues with the tests. Reviewed-by: darcy
--HG--
extra : convert_revision : cfbc790817690e082944d3d485fe272038e3c8ca