8024283: 10 nashorn tests fail with similar stack trace InternalError with cause being NoClassDefFoundError Summary: Fix pre-existing 292 bug tickled by combo of nashorn code and MethodHandleInfo changes Reviewed-by: jrose Contributed-by: vladimir.x.ivanov@oracle.com
--HG--
extra : convert_revision : 9cc74675a8548c6bbbda66d919953f65ea2813e3