8078144: many nightly tests failed due to NoSuchMethodError: sun.management.ManagementFactoryHelper.getDiagnosticMXBean Reviewed-by: alanb, sla
--HG--
extra : convert_revision : e3ac9940a2db3667a97e6af1797c6fa8d9a5d046