8183038: Minimal vm slowdebug build fails with undefined reference to MetaspaceShared::is_valid_shared_method Summary: added missing NOT_CDS_RETURN_(false) Reviewed-by: jiangli, coleenp
--HG--
extra : rebase_source : 45a623d43c6941c9dc37d4194edf961f4e04b701
extra : convert_revision : 7ae3e5da7a4940ec4b16cb40436aa4c22850142f