8009154: Missing cast in method reference bridge leads to NoSuchMethodError Summary: Missing cast in generated method reference bridge Reviewed-by: rfield, jjg
--HG--
extra : convert_revision : a708c5f1da0649ebc0df19027e74d2bb336e3d58