8173373: C1: NPE is thrown instead of LinkageError when accessing inaccessible field on NULL receiver Summary: Deoptimize if receiver null check of unresolved field access fails to throw NoClassDefFoundError instead of NPE. Reviewed-by: vlivanov
--HG--
extra : convert_revision : 7fc3380005949146bbb8699989fa3f6f8464a0d5