8174725: JVM should throw NoClassDefFoundError if ACC_MODULE is set in access_flags Summary: Check if ACC_MODULE is set, and if so, throw NoClassDefFoundError exception Reviewed-by: dholmes, alanb, acorn, coleenp, lfoltan, gtriantafill
--HG--
extra : convert_revision : fcc911c59d4cbd29abbe32fc4e471362c46fe85b