8078144: many nightly tests failed due to NoSuchMethodError: sun.management.ManagementFactoryHelper.getDiagnosticMXBean Reviewed-by: alanb, sla
--HG--
extra : convert_revision : 272337a233422432b4e5a0b2eca09ff6a2d79105