8056051: int[]::clone causes "java.lang.NoClassDefFoundError: Array" Reviewed-by: mcimadamore, vromero
--HG--
extra : convert_revision : 7193d3fefda64af7a2dc935943ecfc467e4002aa